INSERT INTO AUTHOR (name, creation_date, updated_date)
VALUES 
   ('Author 1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
   ('Author 2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
   ('Author 3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
   ('Author 4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
   ('Author 5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);