INSERT INTO AUTHOR (name_author, creation_date_author, updated_date_author)
VALUES 
   ('Author 1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
   ('Author 2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
   ('Author 3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
   ('Author 4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
   ('Author 5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);